### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by hoodie** [tsurai/libstrophe-rs#1]
Hi,
I've  found this crate and would like to use it. However there is almost no doc and no examples, but you published it on crates.io.
Are you using it yourself somewhere? Does it work?

Thank you

**Comment by tsurai** [comment]
Hi hoodle,

this crate is a direct foreign function interface over the original libstrophe C library. That means that all functions have the same name as the C library and behave the same way. You can look at the examples from the original library ([https://github.com/strophe/libstrophe/tree/master/examples](https://github.com/strophe/libstrophe/tree/master/examples)) to get an idea of how it's being used.
I'll adjust and add those examples to this library later today.

That being said, I've been wanting to write a new version that uses a proper safe high level wrapper but havn't gotten around to it yet. Maybe I'll do so in the next weeks but when I do I'll be sure to include examples of the changes ;)

**Comment by hoodie** [comment]
Hi, thanks, that sounds awesome. I found the direct mapping to the c-lib and considered just pull-requesting in some examples, but then, I haven't done anything with strophe yet at all and thought, maybe you already use it somewhere internally anyway.
Cheers

update:
just a side-note: this should probably be called `libstrophe-sys` on crates.io. If you intend to continue developing this, you should perhaps move these bindings into a `-sys` crate and use this crate for the higher level API.

**Comment by flosse** [comment]
I'd love to see some examples too!

> this should probably be called libstrophe-sys on crates.io.

+1

**Comment by tsurai** [comment]
I've added three examples from the official documentation showing the basic usage of libstrophe. Another example for a simple bot will follow tomorrow after which I'll publish a new crate under the name libstrophe-sys.

Please tell me if you have any more advices or find mistakes in my example code. Thanks a lot for your help !

**_Note:**_ I'm now linking against a newer version of libstrophe which means that you might have to compile the c library from source if the version in your package manager is too old.

**Comment by hoodie** [comment]
Thank you very much :D

**Comment by tsurai** [comment]
Just added the last examples and re-published the crate as libstrophe-sys (https://crates.io/crates/libstrophe-sys/)
